server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: root

  #  mvc: # 생략 가능(mustache 의존성 추가했기 때문)
  #    view:
  #      prefix: /templates/
  #      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 974070161222-dgu16tsiv1fqrjljqecask65j573jluj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile